title: Max Tarlov
tagline: Bay Area Linguist
description: A linguistics and natural language processing specialist in the SF Bay Area
show_downloads: false
# google_analytics:
theme: jekyll-theme-cayman
collections:
  info_pages:
    output: true
  projects:
    output: true
    # order:
    #   - interview-bot-demo.md
    #   - interview-bot-nb.md
    #   - SPOT.md