title: Max Tarlov
description: A linguistics and natural language processing specialist in the SF Bay Area
show_downloads: false
# google_analytics:
theme: jekyll-theme-cayman
collections:
  projects:
    output: true